spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    username: webdb
    #username: ENC(/NOwzvlVuCahj8mqMMDKaQ==)
    url: jdbc:mysql://192.168.31.7:49154/web_db?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    password: p@ssword123
    #password: ENC(U4dzPkpNF4ugZYHgZGNoK3w8vVDLwqoq)
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: local
  redis:
    host: localhost
    port: 6379
logging:
  level:
    root: info
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

## 프로퍼티 암호화 설정
jasypt:
  encryptor:
    bean: jasyptStringEncryptor

naver.shortUrl: https://openapi.naver.com/v1/util/shorturl
naver.clientId: DIQ9kSya80pQ27fPvpk_
naver.clientSecret: 37dTiG6CHT